cron.expression=0 0 14 30 * *
cron.responder.expression=0 30 8 5 * *

server.tomcat.basedir=/localFiles/tmp

oauth.client_secret=${OAUTH_CLIENT_SECRET}
domain.batchSize=${DOMAIN_BATCH_SIZE}
batch.size=${RESPONDER_BATCH_SIZE}

fulfillment.url=https://partner-fulfillment.central-stage-cust.kpsazc.dgtl.kroger.com

domain.file.name=/localFiles/tmp/KrogerFulfillments.csv

sftp.backup.path=/mnt/DisneyBatchJobData/Stage/kroger_us_AsOf_Reconciliation_backup.csv



#Disney Stage

sftp.host=s-6aff3ee05bfc42929.server.transfer.us-east-1.amazonaws.com
sftp.username=KROGER_US-SFTP-QA
sftp.remotePath=/Reconciliation/kroger_us_AsOf_Reconciliation.csv
sftp.keyPath=Key/kroger_api
sftp.localPath=/localFiles/tmp/disneyLocalFile.csv

sftp.responder.remotePath=/ResponderFile/{fileName}
sftp.responder.host=s-6aff3ee05bfc42929.server.transfer.us-east-1.amazonaws.com
sftp.responder.username=KROGER_US-SFTP-QA
domain.retry.attempts=3
benefit.url=https://partner-fulfillment.central-stage-cust.kpsazc.dgtl.kroger.com
orchestrator.retry=3

#Local Stage

#sftp.host=10.32.10.252
#sftp.username=ecadmin
#sftp.remotePath=/home/ecadmin/disneyTempData/kroger_us_AsOf_Reconciliation.csv
#
#sftp.responder.remotePath=/home/ecadmin/disneyTempData/{fileName}
#sftp.keyPath=Key/id_rsa
#sftp.responder.host=10.32.10.252
#sftp.responder.username=ecadmin
#domain.retry.attempts=3
#benefit.url=https://partner-fulfillment.central-stage-cust.kpsazc.dgtl.kroger.com
#orchestrator.retry=2
