cron.expression=0 30 4 3 * *
cron.responder.expression=0 30 4 6 * *

server.tomcat.basedir=/localFiles/tmp

sftp.host=s-5826727fa9b043acb.server.transfer.us-east-1.amazonaws.com
sftp.username=KROGER_US-SFTP-PROD
sftp.keyPath=Key/kroger_api
sftp.remotePath=/Reconciliation/kroger_us_AsOf_Reconciliation.csv
sftp.localPath=/localFiles/tmp/disneyLocalFile.csv

domain.file.name=/localFiles/tmp/KrogerFulfillments.csv

sftp.backup.path=/mnt/DisneyBatchJobData/Production/kroger_us_AsOf_Reconciliation_backup.csv


oauth.client_id=partnerfulfillmentmonthlyreconciliationprod-fe58b0556ff79f0ef3bfc5498d5abfba5544702522992289661
oauth.client_secret=${OAUTH_CLIENT_SECRET}
oauth.token_url=https://api.kroger.com/v1/connect/oauth2/token
oauth.timeout=10

fulfillment.url=https://partner-fulfillment.central-prod-cust.kpsazc.dgtl.kroger.com
domain.batchSize=${DOMAIN_BATCH_SIZE}

sftp.localPath.reconciliation=/mnt/DisneyBatchJobData/Production/{fileName}
sftp.remotePath.reconciliation=/review/Reconciliation/{fileName}
sftp.username.local.reconciliation=ecadmin
sftp.username.remote.reconciliation=KROGER_US-SFTP-PROD
sftp.host.local.reconciliation=10.32.10.252
sftp.host.remote.reconciliation=s-5826727fa9b043acb.server.transfer.us-east-1.amazonaws.com
sftp.key.local.reconciliation=Key/id_rsa
sftp.key.remote.reconciliation=Key/kroger_api

batch.size=${RESPONDER_BATCH_SIZE}
sftp.responder.remotePath=/ResponderFile/{fileName}
sftp.responder.host=s-5826727fa9b043acb.server.transfer.us-east-1.amazonaws.com
sftp.responder.username=KROGER_US-SFTP-PROD
domain.retry.attempts=3
benefit.url=https://partner-fulfillment.central-prod-cust.kpsazc.dgtl.kroger.com
orchestrator.retry=3