cron.expression=0 */5 * ? * *
cron.responder.expression=0 0 5 3 * *

sftp.host=10.32.10.252
sftp.username=ecadmin
sftp.keyPath=Key/id_rsa
sftp.remotePath=/mnt/DisneyBatchJobData/Stage/kroger_us_AsOf_Reconciliation.csv
sftp.localPath=disneyLocalFile.csv

oauth.client_id=partnerfulfillmentmonthlyreconciliation-24326124303424514d70596c697a2e76357454634571566874584a354f6d746e64554d654767746831487964796a6d7439657175392f794430356e365002974344580877798
oauth.client_secret=VLsnn_B7_7bKjb2B1Sh4UKfJVbqmxqlZCrteEmDz
oauth.token_url=https://api-ce.kroger.com/v1/connect/oauth2/token
oauth.timeout=10
oauth.claims=urn:com:kroger:partner-fulfillment:write urn:com:kroger:partner-benefits:write urn:com:kroger:partner-benefits:read
oauth.retry=3

sftp.backup.path=/mnt/DisneyBatchJobData/Stage/kroger_us_AsOf_Reconciliation_backup.csv


fulfillment.url=https://partner-fulfillment.central-dev-cust.kpsazc.dgtl.kroger.com
domain.batchSize=3000
domain.file.name=DisneyFulfillments.csv

sftp.localPath.reconciliation=/mnt/DisneyBatchJobData/Stage/{fileName}
sftp.remotePath.reconciliation=/review/Reconciliation/{fileName}
sftp.remotePath.responder=/ResponderFile/{fileName}
sftp.username.local.reconciliation=ecadmin
sftp.username.remote.reconciliation=KROGER_US-SFTP-QA
#sftp.username.remote.reconciliation=KROGER_US-SFTP-PROD
sftp.host.local.reconciliation=10.32.10.252
sftp.host.remote.reconciliation=s-6aff3ee05bfc42929.server.transfer.us-east-1.amazonaws.com
#sftp.host.remote.reconciliation=s-5826727fa9b043acb.server.transfer.us-east-1.amazonaws.com
sftp.key.local.reconciliation=Key/id_rsa
sftp.key.remote.reconciliation=Key/kroger_api

batch.size=100
sftp.responder.remotePath=/mnt/DisneyBatchJobData/Stage/{fileName}
#sftp.responder.host=s-6aff3ee05bfc42929.server.transfer.us-east-1.amazonaws.com
sftp.responder.host=10.32.10.252
sftp.responder.username=ecadmin
domain.retry.attempts=3
benefit.url=https://partner-fulfillment.central-stage-cust.kpsazc.dgtl.kroger.com
orchestrator.retry=3
